In [1]:
#numpy - NumPy is a Python library used for working with arrays, NumPy stands for Numerical Python.
#In Python we have lists that serve the purpose of arrays, but they are slow to process
#NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.
#Arrays are very frequently used in data science, where speed and resources are very important.

#Why is NumPy Faster Than Lists?
#NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and 
#manipulate them very efficiently.

#This behavior is called locality of reference in computer science.

#This is the main reason why NumPy is faster than lists. Also it is optimized to work with 
#latest CPU architectures.

#Creating Arrays
import numpy as np

print(np.__version__)

#Create a 0-D array with value
arr = np.array(42)
print(arr)

#Create a 1-D array with value
arr = np.array([1, 2, 3, 4, 5])
print(arr)

#Create a 2-D array with value
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

#Create a 3-D array with value - An array that has 2-D arrays (matrices) as its elements is called 3-D array.
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)


1.20.3
42
[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [2]:
#Check how many dimensions the arrays have
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [3]:
#Numpy Array Indexing
#Array indexing is the same as accessing an array element.
#You can access an array element by referring to its index number.

import numpy as np

#Get the second element from the following array
arr = np.array([1, 2, 3, 4])
print(arr[1])

#Get third and fourth elements from the following array and add them
arr = np.array([1, 2, 3, 4])
print(arr[2] + arr[3])

2
7


In [4]:
#NumPy Array Slicing
#Slicing in python means taking elements from one given index to another given index.
#We pass slice instead of index like this: [start:end]

import numpy as np

#slice elements from index 1 to index 5
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])

#Slice elements from index 4 to the end of the array
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[4:])

#Slice elements from the beginning to index 4 (not included)
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[:4])

[2 3 4 5]
[5 6 7]
[1 2 3 4]


In [5]:

#numpy copy and view

#The main difference between a copy and a view of an array is that the copy is a new array, 
#and the view is just a view of the original array.

#copy

#The copy owns the data and any changes made to the copy will not affect original array, and 
#any changes made to the original array will not affect the copy.
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(x)
print(arr)

[1 2 3 4 5]
[42  2  3  4  5]


In [6]:
#view
#The view SHOULD be affected by the changes made to the original array.
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [7]:
#The original array SHOULD be affected by the changes made to the view.
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


In [8]:
#Shape of an Array
#The shape of an array is the number of elements in each dimension

#Print the shape of a 2-D array:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [9]:
#Reshape
#Reshaping means changing the shape of an array.

#Reshape From 1-D to 2-D
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [10]:
#Numpy ufunc()
#ufuncs stands for "Universal Functions" and they are NumPy functions

#add elements in x & y
import numpy as np

x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = np.add(x, y)

print(z)

#Another way of doing it is to iterate over both of the lists and then sum each elements.
x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = []

for i, j in zip(x, y):
  z.append(i + j)
print(z)

[ 5  7  9 11]
[5, 7, 9, 11]


In [11]:
#Numpy Simple Arithmetic

#You could use arithmetic operators + - * / directly between NumPy arrays
import numpy as np

#Addition
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.add(arr1, arr2)

print(newarr)

#Subtraction
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.subtract(arr1, arr2)

print(newarr)

#Multiplication
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.multiply(arr1, arr2)

print(newarr)

#Division
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 10, 8, 2, 33])

newarr = np.divide(arr1, arr2)

print(newarr)

#Mod & Reminder - same
#mod
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.mod(arr1, arr2)

print(newarr)

#Reminder
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.remainder(arr1, arr2)

print(newarr)

[30 32 34 36 38 40]
[-10  -1   8  17  26  35]
[ 200  420  660  920 1200 1500]
[ 3.33333333  4.          3.          5.         25.          1.81818182]
[ 1  6  3  0  0 27]
[ 1  6  3  0  0 27]


In [12]:
#Rounding 
import numpy as np

#1Truncation & fix
#Remove the decimals, and return the float number closest to zero
arr = np.trunc([-3.1666, 3.6667])
print(arr)

arr = np.fix([-3.1666, 3.6667])
print(arr)

#2Rounding
#The around() function increments preceding digit or decimal by 1 if >=5 else do nothing
arr = np.around([3.1666, 2])
print(arr)


#3Floor
#The floor() function rounds off decimal to nearest lower integer.
arr = np.floor([-3.1666, 3.6667])
print(arr)

#4Ceil
#The ceil() function rounds off decimal to nearest upper integer.
arr = np.ceil([-3.1666, 3.6667])
print(arr)

[-3.  3.]
[-3.  3.]
[3. 2.]
[-4.  3.]
[-3.  4.]


In [13]:
#summation
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2])

print(newarr)

#Products
import numpy as np

arr = np.array([1, 2, 3, 4])

x = np.prod(arr)

print(x)

#Numpy Set Operations
import numpy as np

#Union
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr = np.union1d(arr1, arr2)

print(newarr)

#Intersection
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr = np.intersect1d(arr1, arr2)

print(newarr)

#Finding Difference
set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])

newarr = np.setdiff1d(set2, set1)

print(newarr)

12
24
[1 2 3 4 5 6]
[3 4]
[5 6]


In [14]:
#LCM & GCD
import numpy as np

#Find the LCM of the following two numbers:
num1 = 4
num2 = 6

x = np.lcm(num1, num2)

print(x)

#Find the GCD of the following two numbers:
import numpy as np

num1 = 6
num2 = 9

x = np.gcd(num1, num2)

print(x)

12
3
